# Generated by Django 3.2.24 on 2024-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Believer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='believers')),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('joined_date', models.DateField()),
                ('category', models.CharField(choices=[('child', 'Child'), ('teenager', 'Teenager'), ('adult', 'Adult'), ('elders', 'Elders')], max_length=100)),
                ('service_group', models.CharField(choices=[('none', 'None'), ('prophet', 'Prophet'), ('apostle', 'Apostle'), ('pastor', 'Pastor'), ('evangelical', 'Evangelical'), ('deacons', 'Deacons'), ('singer', 'Singer'), ('elder', 'Elder')], max_length=100)),
                ('status', models.CharField(choices=[('pastor', 'Pastor'), ('untaken', 'Untaken')], max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials')),
                ('contact_phone', models.CharField(max_length=20)),
                ('date_served', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_chat')),
                ('documents', models.FileField(blank=True, null=True, upload_to='group_chat_documents')),
                ('group', models.CharField(choices=[('prayer', 'Prayer'), ('classes', 'classes'), ('compassion', 'Compassion'), ('quires', 'Quires'), ('pastors', 'Pastors'), ('deacons', 'Deacons'), ('elders', 'Elders'), ('teachers', 'Teachers')], max_length=100)),
                ('members', models.ManyToManyField(to='staff.Believer')),
            ],
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastor', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fellowships')),
                ('documents', models.FileField(blank=True, null=True, upload_to='fellowship_documents')),
                ('believers', models.ManyToManyField(to='staff.Believer')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('lecturer', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('started_date', models.DateField()),
                ('end_date', models.DateField()),
                ('documents', models.FileField(upload_to='education_documents')),
                ('messages', models.TextField()),
                ('learners', models.ManyToManyField(to='staff.Believer')),
            ],
        ),
    ]
