# Generated by Django 3.2.24 on 2024-03-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_expense_income_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Stock',
        ),
    ]
